language: go

go:
  - 1.16

before_install:
  # We need Python to run pygmentize for generating HTML.
  - sudo apt-get update
  - sudo apt-get install python

install:
  - go mod download

script:
  - tools/build

env:
  - VERBOSE=1 TESTING=1
